# Generated by Django 3.0 on 2025-03-05 14:51

from django.db import migrations


def transfer_data(apps, schema_editor):
    OldProfile = apps.get_model("oc_lettings_site", "Profile")
    NewProfile = apps.get_model("profiles", "Profile")

    for old_instance in OldProfile.objects.all():
        NewProfile.objects.create(
            user=old_instance.user,
            favorite_city=old_instance.favorite_city,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(transfer_data),
    ]
