# Generated by Django 3.0 on 2025-03-05 13:32

from django.db import migrations


def transfer_data(apps, schema_editor):
    OldAddress = apps.get_model("lettings", "Address")
    NewAddress = apps.get_model("lettings", "Address")

    OldLetting = apps.get_model("lettings", "Letting")
    NewLetting = apps.get_model("lettings", "Letting")

    for old_instance in OldAddress.objects.all():
        new_address = NewAddress.objects.create(
            number=old_instance.number,
            street=old_instance.street,
            city=old_instance.city,
            state=old_instance.state,
            zip_code=old_instance.zip_code,
            country_iso_code=old_instance.country_iso_code,
        )

        letting_instance = OldLetting.objects.get(address=old_instance)
        NewLetting.objects.create(
            title=letting_instance.title,
            address=new_address,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("lettings", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(transfer_data),
    ]
