# Generated by Django 3.0 on 2025-03-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20250305_1353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
